//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceProductsChanges
    {
        public long ID { get; set; }
        public string Операция { get; set; }
        public long Продукт { get; set; }
        public Nullable<decimal> СтараяСтоимость { get; set; }
        public decimal НоваяСтоимость { get; set; }
    }
}
